//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsignmentRegisteredFacilities
    {
        public int Id { get; set; }
        public int DeclarationId { get; set; }
        public int ConsignmentId { get; set; }
        public short FacilitySequenceNumeric { get; set; }
        public string FacilityID { get; set; }
        public string FacilityType { get; set; }
    
        public virtual Consignments Consignments { get; set; }
        public virtual Declarations Declarations { get; set; }
    }
}
