//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsignmentPackagesMeasures
    {
        public int Id { get; set; }
        public Nullable<int> DeclarationId { get; set; }
        public int PackagesSequenceNumeric { get; set; }
        public string PackageMeasureQualifier { get; set; }
        public Nullable<decimal> TotalPackageQuantity { get; set; }
        public Nullable<decimal> GrossMassMeasure { get; set; }
        public string TypeCode { get; set; }
        public string MarksNumbers { get; set; }
        public Nullable<int> ConsignmentId { get; set; }
    
        public virtual Consignments Consignments { get; set; }
        public virtual Declarations Declarations { get; set; }
    }
}
