//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consignments()
        {
            this.ConsignmentPackagesMeasures = new HashSet<ConsignmentPackagesMeasures>();
            this.ConsignmentRegisteredFacilities = new HashSet<ConsignmentRegisteredFacilities>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeclarationId { get; set; }
        public short SequenceNumeric { get; set; }
        public string CargoDescription { get; set; }
        public Nullable<int> LastReleaseFromWarehousInd { get; set; }
        public string ExportationCountryCode { get; set; }
        public string LoadingLocation { get; set; }
        public string TransportContractDocumentID { get; set; }
        public string TransportContractDocumentTypeCode { get; set; }
        public Nullable<System.DateTime> TransportContractDocumentIssueDateTime { get; set; }
        public string SecondCargoID { get; set; }
        public string ThirdCargoID { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public string UnloadingLocationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentPackagesMeasures> ConsignmentPackagesMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentRegisteredFacilities> ConsignmentRegisteredFacilities { get; set; }
        public virtual Declarations Declarations { get; set; }
    }
}
