//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declarations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Declarations()
        {
            this.ConsignmentPackagesMeasures = new HashSet<ConsignmentPackagesMeasures>();
            this.ConsignmentRegisteredFacilities = new HashSet<ConsignmentRegisteredFacilities>();
            this.Consignments = new HashSet<Consignments>();
            this.DeclarationTaxes = new HashSet<DeclarationTaxes>();
            this.SupplierInvoices = new HashSet<SupplierInvoices>();
        }
    
        public int Id { get; set; }
        public string AgentFileReferenceID { get; set; }
        public Nullable<System.DateTime> AcceptanceDateTime { get; set; }
        public string DeclarationOfficeID { get; set; }
        public string DeclarationNumber { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
        public string TypeCode { get; set; }
        public Nullable<System.DateTime> TaxationDateTime { get; set; }
        public string ExternalDeclarationID { get; set; }
        public string VersionID { get; set; }
        public Nullable<decimal> ExpenseLoadingFactor { get; set; }
        public string AutonomyRegionType { get; set; }
        public string TehilaDeclarationID { get; set; }
        public Nullable<System.DateTime> ReleaseDateTime { get; set; }
        public Nullable<decimal> TotalDealValueAmountNIS { get; set; }
        public Nullable<decimal> CifValueNIS { get; set; }
        public Nullable<decimal> TaxAssessedAmount { get; set; }
        public string AgentID { get; set; }
        public string RoleCode { get; set; }
        public string GovernmentProcedure { get; set; }
        public string ImporterID { get; set; }
        public string ImporterRoleCode { get; set; }
        public string EntitlementTypeCode { get; set; }
        public string IssueLocation { get; set; }
        public string ImporterName { get; set; }
        public string ImporterCountry { get; set; }
        public string PreviousDocument { get; set; }
        public string PreviousDocumentType { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string DeclarationStatusCode { get; set; }
        public Nullable<int> CustomsStatus { get; set; }
        public Nullable<decimal> TotalMADDealValueAmountNIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentPackagesMeasures> ConsignmentPackagesMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentRegisteredFacilities> ConsignmentRegisteredFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignments> Consignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationTaxes> DeclarationTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInvoices> SupplierInvoices { get; set; }
    }
}
