//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclarationTaxes
    {
        public int Id { get; set; }
        public int DeclarationId { get; set; }
        public Nullable<decimal> AdValoremTaxBaseAmount { get; set; }
        public string TaxTypeCode { get; set; }
        public decimal Amount { get; set; }
        public decimal DeferedTaxAmount { get; set; }
    
        public virtual Declarations Declarations { get; set; }
    }
}
