//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string URL { get; set; }
        public string FileName { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> CustomsId { get; set; }
        public string InternalID { get; set; }
        public Nullable<int> CustomsStatus { get; set; }
        public string ErrorDesc { get; set; }
        public Nullable<decimal> RelatedEntity { get; set; }
        public Nullable<decimal> RelatedID { get; set; }
    }
}
