//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAttribute
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PointerID { get; set; }
        public Nullable<decimal> DocID { get; set; }
        public string Attribute { get; set; }
        public string Attribute_Vlaue { get; set; }
    }
}
