//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoiceItems
    {
        public int Id { get; set; }
        public int DeclarationId { get; set; }
        public Nullable<int> SupplierInvoiceId { get; set; }
        public int LineNumber { get; set; }
        public string CustomsBookType { get; set; }
        public string TaxExemptCode { get; set; }
        public string OptionalTama { get; set; }
        public string SalesTaxExemptionType { get; set; }
        public bool IsUsed { get; set; }
        public decimal CustomsValueAmount { get; set; }
        public string AmountType { get; set; }
        public string ClassificationID { get; set; }
        public string ClassificationIdentificationTypeCode { get; set; }
        public string TariffQuantity { get; set; }
        public string OriginCountryCode { get; set; }
        public string DutyRegimeCode { get; set; }
        public string MeasureQualifier { get; set; }
    
        public virtual SupplierInvoices SupplierInvoices { get; set; }
    }
}
