//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsExternal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierInvoices()
        {
            this.SupplierInvoiceItems = new HashSet<SupplierInvoiceItems>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeclarationId { get; set; }
        public int SequenceNumeric { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime IssueDateTime { get; set; }
        public string InvoiceTypeCode { get; set; }
        public bool IsPrefarenceDocumentInd { get; set; }
        public string PrefarenceDocumentType { get; set; }
        public string PaymentType { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal RateNumeric { get; set; }
        public string SupplierID { get; set; }
        public string TradeTermsConditionCode { get; set; }
        public string LocationID { get; set; }
        public string CurrencyCode { get; set; }
    
        public virtual Declarations Declarations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInvoiceItems> SupplierInvoiceItems { get; set; }
    }
}
